services:
  postgres-container:
    image: postgres:17-alpine
    container_name: postgres-container
    env_file:
      - ./env/core.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_container_db:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./env/core.env
    ports:
      - "8080:8080"

volumes:
  postgres_container_db:
